Repository team-essence/TAoSK, pull requests merged in 2021-12, with the labels that each got.

#112 マイページのスタイルング
  frontend/public/images/my-page_background.webp
  frontend/public/index.html
  frontend/public/svg/edit-button.svg
  frontend/public/svg/my-page-user_background.svg
  frontend/public/svg/myPageStatus/achievement.svg
  frontend/public/svg/myPageStatus/design.svg
  frontend/public/svg/myPageStatus/motivation.svg
  frontend/public/svg/myPageStatus/plan.svg
  frontend/public/svg/myPageStatus/solution.svg
  frontend/public/svg/myPageStatus/technology.svg
  frontend/public/svg/tag-triangle_background.svg
  frontend/public/svg/tag_background.svg
  frontend/public/svg/user-status_background.svg
  frontend/public/svg/user-tags_background.svg
  frontend/src/components/models/myPage/MyPageStatus.tsx
  frontend/src/components/models/myPage/MyPageStatusCard.tsx
  frontend/src/components/models/myPage/MyPageTags.tsx
  frontend/src/components/models/myPage/MyPageUserInfo.tsx
  frontend/src/components/ui/button/EditButton.tsx
  frontend/src/components/ui/header/ProjectListHeader.tsx
  frontend/src/components/ui/tag/Tag.tsx
  frontend/src/pages/mypage/MyPage.tsx
  frontend/src/pages/mypage/mypage.gql
  frontend/src/styles/myPageStatusLabel/LabelColor.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/exp/exp.ts
  frontend/src/utils/status/status.ts
Labels: スタイリング, バックエンド, フロントエンド

#110 Feat/projects list
  api/src/list-sorts/dto/removeListSort.input.ts
  api/src/list-sorts/list-sorts.resolver.ts
  api/src/list-sorts/list-sorts.service.ts
  api/src/lists/dto/removeList.input.ts
  api/src/lists/dto/updateList.input.ts
  api/src/lists/lists.resolver.ts
  api/src/lists/lists.service.ts
  api/src/schema.gql
  frontend/package.json
  frontend/public/svg/spread.svg
  frontend/src/components/models/task/Column.tsx
  frontend/src/components/models/task/ColumnList.tsx
  frontend/src/components/models/task/CreateTaskButton.tsx
  frontend/src/components/models/task/SmallPopover.tsx
  frontend/src/components/models/task/TaskCard.tsx
  frontend/src/components/models/task/TaskList.tsx
  frontend/src/components/ui/modal/BasicPopover.tsx
  frontend/src/consts/dropType.ts
  frontend/src/hooks/useControlTextArea.ts
  frontend/src/hooks/usePopover.ts
  frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectList/projectDetail/projectDetail.gql
  frontend/src/styles/theme.ts
  frontend/src/types/popover.ts
  frontend/yarn.lock
Labels: バックエンド, フロントエンド

#122 プロジェクト詳細ページ左下(自分の情報をスライリング)
  api/src/projects/project.ts
  api/src/projects/projects.resolver.ts
  api/src/projects/projects.service.ts
  api/src/schema.gql
  frontend/public/index.html
  frontend/public/svg/project-detail-my-info_background.svg
  frontend/public/svg/projectStatuses/achievement.svg
  frontend/public/svg/projectStatuses/design.svg
  frontend/public/svg/projectStatuses/motivation.svg
  frontend/public/svg/projectStatuses/plan.svg
  frontend/public/svg/projectStatuses/solution.svg
  frontend/public/svg/projectStatuses/technology.svg
  frontend/public/svg/user-name_background.svg
  frontend/src/components/models/project/ProjectMyBars.tsx
  frontend/src/components/models/project/ProjectMyInfo.tsx
  frontend/src/components/models/project/ProjectMyStatuses.tsx
  frontend/src/consts/bar.ts
  frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectList/projectDetail/projectDetail.gql
  frontend/src/styles/fontFamily/fontFamily.ts
  frontend/src/styles/theme.ts
Labels: スタイリング, フロントエンド

#147 諸々の修正とアカウント設定モーダルの作成
  frontend/public/svg/projectStatuses/achievement.svg
  frontend/public/svg/projectStatuses/design.svg
  frontend/public/svg/projectStatuses/motivation.svg
  frontend/public/svg/projectStatuses/plan.svg
  frontend/public/svg/projectStatuses/solution.svg
  frontend/public/svg/projectStatuses/technology.svg
  frontend/src/components/models/employee/EmployeePopover.tsx
  frontend/src/components/models/employee/EmployeeStatus.tsx
  frontend/src/components/models/project/ProjectDrawer.tsx
  frontend/src/components/models/project/ProjectMyStatuses.tsx
  frontend/src/components/models/task/TaskCard.tsx
  frontend/src/components/models/task/TaskColumn.tsx
  frontend/src/components/models/task/TaskColumnList.tsx
  frontend/src/components/models/task/TaskList.tsx
  frontend/src/components/models/user/UserAccountSettingModal.tsx
  frontend/src/components/ui/button/CoarseButton.tsx
  frontend/src/components/ui/header/ProjectDetailHeader.tsx
  frontend/src/components/ui/header/ProjectListHeader.tsx
  frontend/src/components/ui/modal/Modal.tsx
  frontend/src/components/ui/popup/UserMenuPopup.tsx
  frontend/src/hooks/useAccountSettingForm.tsx
  frontend/src/pages/auth/SignIn.tsx
  frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx
  frontend/src/styles/theme.ts
  frontend/src/utils/lib/firebase/firebaseAuth.ts
  frontend/src/utils/lib/firebase/firebaseInitial.ts
Labels: スタイリング, FIX, フロントエンド

#149 feat: ログ周りのスタイルング、mutation & モンスターのHP処理
  api/src/game-logs/dto/newGameLog.input.ts
  api/src/game-logs/game-logs.module.ts
  api/src/game-logs/game-logs.resolver.spec.ts
  api/src/game-logs/game-logs.resolver.ts
  api/src/game-logs/game-logs.service.spec.ts
  api/src/game-logs/game-logs.service.ts
  api/src/lists/dto/newList.input.ts
  api/src/lists/lists.module.ts
  api/src/lists/lists.service.ts
  api/src/projects/dto/endProject.input.ts
  api/src/projects/projects.module.ts
  api/src/projects/projects.resolver.ts
  api/src/projects/projects.service.ts
  api/src/schema.gql
  api/src/tasks/dto/newTask.input.ts
  api/src/tasks/dto/updateTaskSort.input.ts
  api/src/tasks/tasks.module.ts
  api/src/tasks/tasks.service.ts
  api/src/users/users.module.ts
  api/src/users/users.resolver.ts
  api/src/users/users.service.ts
  frontend/src/components/models/project/ProjectGameLog.tsx
  frontend/src/components/models/project/ProjectMonster.tsx
  frontend/src/components/models/project/ProjectRight.tsx
  frontend/src/consts/gameLog.ts
  frontend/src/hooks/useTaskCreateForm.ts
  frontend/src/pages/projectList/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectList/projectDetail/projectDetail.gql
Labels: スタイリング, FIX, バックエンド, フロントエンド

#151 fix: タスク追加時のタスクIDが固定だったので修正
  api/src/tasks/tasks.service.ts
  frontend/src/components/models/task/TaskColumn.tsx
  frontend/src/components/models/task/TaskCreateModal.tsx
  frontend/src/hooks/useTaskCreateForm.ts
Labels: バグ, バックエンド, フロントエンド

#158 fix, refactor: タスク作成モーダルのスタイルの修正, ボタンのスタイル関連のリファクタ, フォントちらつく問題の改善
  frontend/public/index.html
  frontend/public/svg/search-icon.svg
  frontend/src/components/models/project/ProjectDrawer.tsx
  frontend/src/components/models/task/TaskColumn.tsx
  frontend/src/components/models/task/TaskCreateModal.tsx
  frontend/src/components/models/task/TaskStatusPointField.tsx
  frontend/src/components/models/user/UserAccountSettingModal.tsx
  frontend/src/components/ui/avatar/UserAvatarIcon.tsx
  frontend/src/components/ui/avatar/UserCount.tsx
  frontend/src/components/ui/button/CoarseButton.tsx
  frontend/src/components/ui/button/ModalButton.tsx
  frontend/src/components/ui/button/SimpleRoundedButton.tsx
  frontend/src/components/ui/form/CalenderField.tsx
  frontend/src/components/ui/form/ImageInputField.tsx
  frontend/src/components/ui/form/InputField.tsx
  frontend/src/components/ui/form/InputItem.tsx
  frontend/src/components/ui/form/ItemInputField.tsx
  frontend/src/components/ui/form/PasswordField.tsx
  frontend/src/components/ui/form/SearchMemberField.tsx
  frontend/src/components/ui/form/SelectField.tsx
  frontend/src/components/ui/form/TextAreaField.tsx
  frontend/src/components/ui/header/AuthHeader.tsx
  frontend/src/components/ui/modal/Modal.tsx
  frontend/src/components/ui/projectList/ProjectListProjectInfo.tsx
  frontend/src/hooks/useControllTextArea.ts
  frontend/src/hooks/useTextItems.ts
  frontend/src/pages/auth/SignIn.tsx
  frontend/src/pages/auth/SignUp.tsx
  frontend/src/pages/projectList/ProjectList.tsx
  frontend/src/styles/globalStyle.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/calculateSizeBasedOnFigma.ts
Labels: スタイリング, フロントエンド

#161 feat: task completed flag database
  frontend/src/pages/projectDetail/ProjectDetail.tsx
Labels: FIX, フロントエンド

#163 add: タスク作成時にユーザーも追加できるようにした
  api/src/allocations/allocations.resolver.ts
  api/src/allocations/dto/newAllocation.input.ts
  api/src/schema.gql
  api/src/tasks/tasks.resolver.ts
  api/src/tasks/tasks.service.ts
  frontend/src/hooks/useTaskCreateForm.ts
  frontend/src/pages/projectDetail/projectDetail.gql
Labels: FIX, 優先度: 高, バックエンド

#165 fix: ゲームログを最新25件取得してくる
  api/src/game-logs/game-logs.resolver.ts
  api/src/game-logs/game-logs.service.ts
  api/src/projects/projects.service.ts
  api/src/schema.gql
  frontend/src/components/models/project/ProjectRight.tsx
  frontend/src/hooks/useGameLog.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectDetail/projectDetail.gql
Labels: FIX, バックエンド

#169 fix: マイページにあるステータスのグラデーションを変更
  frontend/public/myPageStatus/achievement.png
  frontend/public/myPageStatus/design.png
  frontend/public/myPageStatus/motivation.png
  frontend/public/myPageStatus/plan.png
  frontend/public/myPageStatus/solution.png
  frontend/public/myPageStatus/technology.png
  frontend/public/svg/myPageStatus/achievement.svg
  frontend/public/svg/myPageStatus/design.svg
  frontend/public/svg/myPageStatus/motivation.svg
  frontend/public/svg/myPageStatus/plan.svg
  frontend/public/svg/myPageStatus/solution.svg
  frontend/public/svg/myPageStatus/technology.svg
  frontend/src/components/models/myPage/MyPageStatus.tsx
  frontend/src/components/models/myPage/MyPageStatusCard.tsx
  frontend/src/styles/theme.ts
Labels: スタイリング, FIX, フロントエンド

#173 fix: プレゼンス機能
  api/src/game-logs/game-logs.service.ts
  frontend/src/hooks/usePresence.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/routes/AppRoutes.tsx
Labels: バグ, FIX, バックエンド, フロントエンド

#186 bugfix: ログがキャッシュされないように
  frontend/src/hooks/useGameLog.ts
Labels: バグ, フロントエンド

#188 fix: ヘッダーのロゴを押したらインデックスページに戻る
  frontend/src/components/ui/header/ProjectDetailHeader.tsx
  frontend/src/components/ui/header/ProjectListHeader.tsx
Labels: FIX, フロントエンド

#190 bugfix: プロジェクトリストページのバックグランドイメージがしっかり表示されるように
  frontend/src/pages/projectList/ProjectList.tsx
Labels: FIX, フロントエンド

#193 タスク移動できないバグを修正
  api/src/tasks/tasks.service.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
Labels: バグ, バックエンド, フロントエンド

#199 feat: 職業テーブルの追加
  Makefile
  README.md
  api/.gitignore
  api/package.json
  api/prisma/lib/occupation.ts
  api/prisma/schema.prisma
  api/prisma/seed.ts
  api/src/occupations/occupation.ts
  api/src/occupations/occupations.module.ts
  api/src/occupations/occupations.resolver.spec.ts
  api/src/occupations/occupations.resolver.ts
  api/src/occupations/occupations.service.spec.ts
  api/src/occupations/occupations.service.ts
  api/src/schema.gql
  api/src/users/user.ts
  api/src/users/users.module.ts
  api/yarn.lock
Labels: 新機能, バックエンド

#201 bugfix: 職業テーブルの追加に伴う修正
  api/src/projects/projects.service.ts
  api/src/users/users.service.ts
  frontend/src/components/models/employee/EmployeeInformation.tsx
  frontend/src/components/models/employee/EmployeePopover.tsx
  frontend/src/components/models/myPage/MyPageUserInfo.tsx
  frontend/src/components/models/project/ProjectMyInfo.tsx
  frontend/src/components/models/projectList/ProjectListProjectInfo.tsx
  frontend/src/components/ui/avatar/ManyUserAvatar.tsx
  frontend/src/components/ui/form/SearchMemberField.tsx
  frontend/src/hooks/useTrySignUp.ts
  frontend/src/pages/auth/SignUp.tsx
  frontend/src/pages/auth/document.gql
  frontend/src/pages/auth/signUp.gql
  frontend/src/pages/mypage/MyPage.tsx
  frontend/src/pages/mypage/mypage.gql
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectDetail/getUser.gql
  frontend/src/pages/projectDetail/projectDetail.gql
  frontend/src/pages/projectList/projectList.gql
Labels: バグ, バックエンド, フロントエンド

#206 feat: モンスターのデータを流し込むseedを追加
  Makefile
  README.md
  api/prisma/lib/monster.ts
  api/prisma/schema.prisma
  api/prisma/seed.ts
Labels: 新機能, バックエンド

#205 feat: プロジェクトに一つも参加してない時の画面
  frontend/public/eggs.png
  frontend/public/images/no-projects_background.svg
  frontend/src/components/models/projectList/ProjectListDetail.tsx
  frontend/src/components/models/projectList/ProjectListMonster.tsx
  frontend/src/components/models/projectList/ProjectListProjectInfo.tsx
  frontend/src/pages/projectList/ProjectList.tsx
Labels: スタイリング, FIX, フロントエンド

#204 fix: タスクを完了リスト以外のリストに移動したらロールバックする
  api/src/tasks/tasks.service.ts
Labels: FIX, バックエンド

#207 bugfix: auth周りのエラー処理を修正
  frontend/src/consts/firebaseError.ts
  frontend/src/hooks/useTrySignIn.ts
  frontend/src/hooks/useTrySignUp.ts
Labels: バグ, フロントエンド

#211 fix: 新規登録にて空白だけの場合はdisabledに
  frontend/src/consts/regex.ts
  frontend/src/pages/auth/SignUp.tsx
Labels: バグ, フロントエンド

#198 Feat/edit task modal#134
  .vscode/frontend.code-snippets
  api/src/projects/projects.service.ts
  api/src/tasks/tasks.resolver.ts
  frontend/.vscode/frontend.code-snippets
  frontend/src/components/models/project/ProjectMyInfo.tsx
  frontend/src/components/models/task/TaskCard.tsx
  frontend/src/components/models/task/TaskCreateModal.tsx
  frontend/src/components/models/task/TaskEditModal.tsx
  frontend/src/components/models/task/TaskEditOverviewField.tsx
  frontend/src/components/models/task/TaskEditStatusPointField.tsx
  frontend/src/components/models/task/TaskEditTitleField.tsx
  frontend/src/components/models/task/TaskStatusPointField.tsx
  frontend/src/components/models/user/UserAccountSettingModal.tsx
  frontend/src/components/ui/button/CoarseRedOxideButton.tsx
  frontend/src/components/ui/form/CalenderField.tsx
  frontend/src/components/ui/modal/Modal.tsx
  frontend/src/components/ui/popup/ConfirmPopup.tsx
  frontend/src/components/ui/textarea/FlexTextarea.tsx
  frontend/src/hooks/useAccountSettingForm.ts
  frontend/src/hooks/useCalculateOverUsers.ts
  frontend/src/hooks/useDeleteTask.ts
  frontend/src/hooks/useModalInterlockingScroll.ts
  frontend/src/hooks/useResizeObserver.ts
  frontend/src/hooks/useSearchMember.ts
  frontend/src/hooks/useTaskEndDateEditForm.ts
  frontend/src/hooks/useTaskOverviewEditForm.ts
  frontend/src/hooks/useTaskStatusPointEditForm.ts
  frontend/src/hooks/useTaskTitleEditForm.ts
  frontend/src/hooks/useTaskUserSelectForm.ts
  frontend/src/hooks/useWatchElementAspect.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectDetail/projectDetail.gql
  frontend/src/styles/theme.ts
  frontend/src/types/task.ts
  frontend/src/utils/checkObjEqual.ts
Labels: 新機能, フロントエンド

#212 fix: 資格と興味あることを17文字以内しか入力させないように
  frontend/src/components/ui/form/ItemInputField.tsx
  frontend/src/consts/certificationsAndInterests.ts
  frontend/src/pages/auth/SignUp.tsx
Labels: FIX, フロントエンド

#214 fix: コメント機能の追加 #134
  .vscode/frontend.code-snippets
  frontend/.vscode/frontend.code-snippets
  frontend/src/components/models/employee/EmployeeInformation.tsx
  frontend/src/components/models/employee/EmployeePopover.tsx
  frontend/src/components/models/task/TaskColumn.tsx
  frontend/src/components/models/task/TaskComment.tsx
  frontend/src/components/models/task/TaskCommentArea.tsx
  frontend/src/components/models/task/TaskCommentInputField.tsx
  frontend/src/components/models/task/TaskEditModal.tsx
  frontend/src/components/models/task/TaskEditOverviewField.tsx
  frontend/src/components/ui/button/CoarseButton.tsx
  frontend/src/components/ui/modal/BasicPopover.tsx
  frontend/src/components/ui/popup/BasicPopover.tsx
  frontend/src/components/ui/popup/ConfirmPopup.tsx
  frontend/src/components/ui/popup/SmallPopover.tsx
  frontend/src/components/ui/textarea/FlexTextarea.tsx
  frontend/src/hooks/useControllTextArea.ts
  frontend/src/hooks/useDeleteTask.ts
  frontend/src/hooks/useHandleChat.ts
  frontend/src/hooks/useShowChats.ts
  frontend/src/hooks/useTaskAddComment.ts
  frontend/src/hooks/useTaskCommentForm.ts
  frontend/src/hooks/useTaskEndDateEditForm.ts
  frontend/src/hooks/useTaskOverviewEditForm.ts
  frontend/src/hooks/useTaskStatusPointEditForm.ts
  frontend/src/hooks/useTaskTitleEditForm.ts
  frontend/src/pages/projectDetail/projectDetail.gql
  frontend/src/types/chat.ts
  frontend/src/types/formField.ts
  frontend/src/types/popover.ts
Labels: 新機能, FIX, フロントエンド

#213 リストの最大縦幅をヘッダーの文字数が変わっても固定にする
  frontend/src/components/models/task/TaskColumn.tsx
  frontend/src/hooks/useElementSize.tsx
Labels: バグ, フロントエンド

#220 bugfix: モンスターの総HPをフロント側で計算する
  api/src/tasks/tasks.service.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
Labels: バグ, バックエンド, フロントエンド

#209 fix: タグのスタイルを新しいスタイルに変更
  frontend/src/components/ui/form/ItemInputField.tsx
Labels: スタイリング, FIX, フロントエンド

#216 bugfix: リスト削除のバグを修正
  api/src/lists/dto/removeList.input.ts
  api/src/lists/lists.module.ts
  api/src/lists/lists.service.ts
  api/src/schema.gql
  frontend/src/components/models/task/TaskColumn.tsx
  frontend/src/pages/projectDetail/projectDetail.gql
Labels: バグ, バックエンド, フロントエンド

#225 add,fix: タスク編集モーダルの完成 (連動スクロール、ポップオーバーの不具合修正)
  frontend/src/components/models/task/TaskComment.tsx
  frontend/src/components/models/task/TaskCommentArea.tsx
  frontend/src/components/models/task/TaskEditModal.tsx
  frontend/src/components/models/task/TaskEditOverviewField.tsx
  frontend/src/components/ui/avatar/UserAvatarIcon.tsx
  frontend/src/components/ui/popup/HoverTriggerPopover.tsx
  frontend/src/hooks/useModalInterlockingScroll.ts
Labels: FIX, フロントエンド

#223 feat: タスクが一つも無い時、卵の画像を表示
  frontend/public/egg.png
  frontend/src/components/models/monster/Monster2DInformation.tsx
  frontend/src/components/models/project/ProjectRight.tsx
  frontend/src/pages/projectDetail/ProjectDetail.tsx
Labels: 新機能, フロントエンド

#221 fix: モンスターのポジションを変える
  frontend/src/components/models/monster/Monster2DInformation.tsx
  frontend/src/components/models/project/ProjectRight.tsx
Labels: スタイリング, FIX, フロントエンド

#232 fix: 最初に開いたタスクのメンバーとステータスが他のタスクに移っても固定されてしまう問題の修正
  Makefile
  frontend/src/components/models/projectList/ProjectListProjectInfo.tsx
  frontend/src/components/models/task/TaskCreateModal.tsx
  frontend/src/components/models/task/TaskEditModal.tsx
  frontend/src/components/ui/avatar/ManyUserAvatar.tsx
  frontend/src/components/ui/avatar/UserCount.tsx
  frontend/src/components/ui/form/SearchMemberField.tsx
  frontend/src/hooks/useSearchMember.ts
  frontend/src/hooks/useTaskCreateForm.ts
  frontend/src/hooks/useTaskStatusPointEditForm.ts
  frontend/src/hooks/useTaskUserSelectForm.ts
  frontend/src/types/taskModal.ts
  frontend/src/types/userData.ts
Labels: FIX, フロントエンド

#233 fix: コメントでユーザーホバー時に職業表示, 完了にあるタスクはアサインを動かせなくする
  frontend/src/components/models/task/TaskComment.tsx
  frontend/src/components/models/task/TaskCommentArea.tsx
  frontend/src/components/models/task/TaskEditModal.tsx
  frontend/src/components/ui/form/SearchMemberField.tsx
  frontend/src/components/ui/popup/SearchTaskPopup.tsx
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectDetail/projectDetail.gql
  frontend/src/types/task.ts
Labels: FIX, フロントエンド

#224 タスク完了時にアニメーションさせる
  api/src/schema.gql
  api/src/tasks/models/udatedTask.model.ts
  api/src/tasks/tasks.resolver.ts
  api/src/tasks/tasks.service.ts
  api/src/tasks/types/updatedTask.type.ts
  api/src/tasks/utils/StatusPointUtil.ts
  frontend/src/components/models/project/ProjectDrawer.tsx
  frontend/src/components/models/task/TaskCard.tsx
  frontend/src/components/models/task/TaskColumn.tsx
  frontend/src/components/models/task/animation/TaskCompleteAnimation.tsx
  frontend/src/components/models/task/animation/config/anim_motivation.json
  frontend/src/components/models/task/animation/config/anim_plan.json
  frontend/src/components/models/task/animation/config/anim_technology.json
  frontend/src/components/ui/loading/Loading.tsx
  frontend/src/hooks/useCompleteAnimation.ts
  frontend/src/hooks/useSetWeaponJson.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectDetail/projectDetail.gql
  frontend/src/styles/theme.ts
  frontend/src/types/completeAnimation.ts
  frontend/src/utils/lib/budoux/budoux.ts
Labels: スタイリング, 新機能, フロントエンド

#244 add: 検索結果のタスクを押下したときにモーダルを表示できるようにした #240
  frontend/src/components/ui/popup/SearchTaskPopup.tsx
  frontend/src/components/ui/popup/TaskCardPopup.tsx
Labels: フロントエンド

#254 add: アカウント設定モーダルのフロントの機能面の処理を追加
  frontend/public/svg/camera.svg
  frontend/src/components/models/task/TaskComment.tsx
  frontend/src/components/models/task/TaskEditOverviewField.tsx
  frontend/src/components/models/task/TaskEditTitleField.tsx
  frontend/src/components/models/user/UserAccountSettingModal.tsx
  frontend/src/components/ui/button/CancelButton.tsx
  frontend/src/components/ui/form/ImageInputField.tsx
  frontend/src/consts/defaultImages.ts
  frontend/src/hooks/useAccountSettingForm.ts
  frontend/src/hooks/useChangeEmailForm.ts
  frontend/src/hooks/useGetCurrentUserData.ts
  frontend/src/hooks/useImageResize.ts
  frontend/src/hooks/useTaskCreateForm.ts
  frontend/src/hooks/useTrySignUp.ts
  frontend/src/hooks/useUpdateUserIconImage.ts
  frontend/src/hooks/useUpdateUserNameForm.ts
  frontend/src/pages/auth/SignUp.tsx
  frontend/src/pages/mypage/mypage.gql
  frontend/src/utils/lib/azure/azureStorageBlob.ts
Labels: スタイリング, 新機能, FIX, フロントエンド

#258 fix: ユーザごとにステータスを振り分けるように
  api/src/tasks/tasks.service.ts
Labels: FIX, バックエンド

#260 add: プロジェクト一覧ページを画面幅の広いディスプレイにも対応
  frontend/public/images/no-projects_background.svg
  frontend/public/svg/bottom_yellow.svg
  frontend/public/svg/button_red.svg
  frontend/public/svg/project-detail_background.svg
  frontend/public/svg/project-detail_title-arrow_left.svg
  frontend/public/svg/project-detail_title-arrow_right.svg
  frontend/public/svg/project-list_background.svg
  frontend/public/svg/project-list_title-background.svg
  frontend/public/svg/検索.png
  frontend/src/components/models/monster/MonsterAvatar.tsx
  frontend/src/components/models/projectList/ProjectListDetail.tsx
  frontend/src/components/models/projectList/ProjectListMonster.tsx
  frontend/src/components/models/projectList/ProjectListProjectInfo.tsx
  frontend/src/components/ui/modal/Modal.tsx
  frontend/src/components/ui/wrapper/ContentWrapper.tsx
  frontend/src/consts/aspect.ts
  frontend/src/pages/projectList/ProjectList.tsx
  frontend/src/styles/theme.ts
  frontend/src/utils/calculateProjectListDetailWidth.ts
  frontend/src/utils/calculateSizeBasedOnFigma.ts
Labels: スタイリング, 優先度: 高, フロントエンド, 改善

#269 fix: プロジェクト一覧画面のスタイリングを修正
  frontend/src/components/ui/wrapper/ContentWrapper.tsx
  frontend/src/pages/projectList/ProjectList.tsx
Labels: スタイリング, バグ, フロントエンド

#277 feat: タスク周りのみのsubscription実装
  api/src/allocations/allocations.resolver.ts
  api/src/allocations/allocations.service.ts
  api/src/chats/chats.resolver.ts
  api/src/chats/chats.service.ts
  api/src/projects/projects.resolver.ts
  api/src/schema.gql
  api/src/tasks/models/udatedTask.model.ts
  api/src/tasks/tasks.resolver.ts
  api/src/tasks/tasks.service.ts
  frontend/src/components/models/task/TaskEditOverviewField.tsx
  frontend/src/components/models/task/TaskEditStatusPointField.tsx
  frontend/src/components/models/task/TaskEditTitleField.tsx
  frontend/src/hooks/subscriptions/useChatSubscription.ts
  frontend/src/hooks/subscriptions/useListsByTaskSubscription.ts
  frontend/src/hooks/useShowChats.ts
  frontend/src/hooks/useTaskCreateForm.ts
  frontend/src/hooks/useTaskEndDateEditForm.ts
  frontend/src/hooks/useTaskOverviewEditForm.ts
  frontend/src/hooks/useTaskStatusPointEditForm.ts
  frontend/src/hooks/useTaskTitleEditForm.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectDetail/projectDetail.gql
Labels: FIX, バックエンド, フロントエンド

#280 feat: オンライン・オフライン周りのsubscription
  api/src/schema.gql
  api/src/users/users.resolver.ts
  api/src/users/users.service.ts
  frontend/src/components/models/employee/EmployeeProjectMembers.tsx
  frontend/src/hooks/subscriptions/useOnlineSubscription.ts
  frontend/src/pages/projectDetail/projectDetail.gql
Labels: 新機能, FIX, バックエンド

#281 feat: リスト周りのsubscription
  api/src/list-sorts/list-sorts.module.ts
  api/src/list-sorts/list-sorts.resolver.ts
  api/src/list-sorts/list-sorts.service.ts
  api/src/lists/lists.resolver.ts
  api/src/lists/lists.service.ts
  api/src/schema.gql
  api/src/tasks/tasks.service.ts
  frontend/src/hooks/subscriptions/useListsByListSortSubscription.ts
  frontend/src/hooks/subscriptions/useListsByListSubscription.ts
  frontend/src/hooks/useInput.ts
  frontend/src/hooks/useProjectDetail.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectDetail/projectDetail.gql
Labels: 新機能, FIX, バックエンド

#283 feat: プロジェク詳細ページの自分のステータス周りのsubscription
  api/src/schema.gql
  api/src/tasks/tasks.resolver.ts
  api/src/tasks/tasks.service.ts
  frontend/src/hooks/subscriptions/useUserByTaskSubscription.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectDetail/projectDetail.gql
Labels: 新機能, バックエンド, フロントエンド

#284 fix: format distance chat message
  frontend/src/components/models/task/TaskComment.tsx
  frontend/src/utils/date/date.ts
Labels: FIX, フロントエンド

#287 feat: 通知周りのsubscription
  api/src/invitations/invitations.resolver.ts
  api/src/invitations/invitations.service.ts
  api/src/projects/projects.resolver.ts
  api/src/projects/projects.service.ts
  api/src/schema.gql
  api/src/users/users.service.ts
  frontend/src/components/models/projectList/ProjectListDetail.tsx
  frontend/src/components/ui/header/ProjectDetailHeader.tsx
  frontend/src/components/ui/popup/InvitationPopup.tsx
  frontend/src/hooks/subscriptions/useUserByTaskSubscription.ts
  frontend/src/hooks/useGetCurrentUserData.ts
  frontend/src/hooks/useProjectCreateForm.ts
  frontend/src/hooks/useSearchMember.ts
  frontend/src/hooks/useShowChats.ts
  frontend/src/hooks/useTaskAddComment.ts
  frontend/src/hooks/useUpdateInterestsAndCertifications.ts
  frontend/src/hooks/useUpdateUserIconImage.ts
  frontend/src/hooks/useUpdateUserNameForm.ts
  frontend/src/pages/mypage/MyPage.tsx
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectDetail/getUser.gql
  frontend/src/pages/projectDetail/projectDetail.gql
  frontend/src/pages/projectList/ProjectList.tsx
Labels: FIX, バックエンド, フロントエンド

#293 bugfix: subscriptionの致命的なバグの修正
  api/src/chats/chats.resolver.ts
  api/src/chats/chats.service.ts
  api/src/list-sorts/list-sorts.resolver.ts
  api/src/list-sorts/list-sorts.service.ts
  api/src/lists/lists.resolver.ts
  api/src/lists/lists.service.ts
  api/src/schema.gql
  api/src/tasks/tasks.resolver.ts
  api/src/tasks/tasks.service.ts
  api/src/users/users.resolver.ts
  frontend/src/hooks/subscriptions/useUserByTaskSubscription.ts
  frontend/src/hooks/useDeleteTask.ts
Labels: バグ, 優先度: 高, バックエンド, フロントエンド

#294 fix: プロジェクト作成の概要のエラーが表示されない問題の修正
  frontend/src/components/models/projectList/ProjectListCreateModal.tsx
  frontend/src/components/ui/form/TextAreaField.tsx
Labels: バグ, FIX, フロントエンド

#295 feat: マイページ周りのsubscriptionの実装
  api/src/certifications/certifications.resolver.ts
  api/src/certifications/certifications.service.ts
  api/src/interests/interests.resolver.ts
  api/src/interests/interests.service.ts
  api/src/schema.gql
  api/src/users/users.resolver.ts
  frontend/src/hooks/useGetCurrentUserData.ts
  frontend/src/pages/projectDetail/getUser.gql
Labels: FIX, バックエンド, フロントエンド

#297 feat: メンバー周りのsubscriptionを実装
  api/src/schema.gql
  api/src/tasks/tasks.module.ts
  api/src/tasks/tasks.resolver.ts
  api/src/tasks/tasks.service.ts
  frontend/src/components/models/employee/EmployeeProjectMembers.tsx
  frontend/src/hooks/subscriptions/useGroupByTaskSubscription.ts
  frontend/src/hooks/subscriptions/useOnlineSubscription.ts
  frontend/src/pages/projectDetail/projectDetail.gql
Labels: FIX, バックエンド, フロントエンド

#298 improve: モーダルの初回のカクつきを若干減らした
  frontend/public/index.html
  frontend/src/components/ui/modal/Modal.tsx
Labels: スタイリング, フロントエンド, 改善

#300 fix: groupList.map is not a function
  frontend/src/components/models/employee/EmployeeProjectMembers.tsx
Labels: バグ, 優先度: 高, フロントエンド

#301 feat: プロジェクト作成周りのsubscriptionを実装
  api/src/projects/projects.resolver.ts
  api/src/projects/projects.service.ts
  api/src/schema.gql
  frontend/src/hooks/useGetCurrentUserData.ts
  frontend/src/hooks/useProjectDetail.ts
  frontend/src/pages/projectDetail/getUser.gql
Labels: FIX, バックエンド, フロントエンド

#303 bugfix: メンバー情報が消えてしまう問題の修正
  frontend/src/hooks/subscriptions/useGroupByTaskSubscription.ts
  frontend/src/hooks/subscriptions/useOnlineSubscription.ts
Labels: バグ, 優先度: 高, フロントエンド

#304 feat: チャットカウント周りのsubscriptionを実装
  api/src/chats/chats.module.ts
  api/src/chats/chats.resolver.ts
  api/src/chats/chats.service.ts
  api/src/schema.gql
  frontend/src/hooks/subscriptions/useListsByChatSubscription.ts
  frontend/src/hooks/useProjectDetail.ts
  frontend/src/pages/projectDetail/projectDetail.gql
Labels: FIX, バックエンド, フロントエンド

#306 add: モーダルを開いた時のアニメーションを付与
  frontend/src/components/ui/modal/Modal.tsx
  frontend/src/styles/animation/modalAnimation.ts
  frontend/src/styles/theme.ts
Labels: スタイリング, 優先度: 高, フロントエンド

#309 feat: タスクが一つも無い時、卵の画像を表示
  api/src/certifications/certifications.service.ts
  api/src/interests/interests.service.ts
  api/src/tasks/tasks.service.ts
  api/src/users/users.service.ts
  frontend/src/components/models/projectList/ProjectListItem.tsx
  frontend/src/pages/projectDetail/getUser.gql
  frontend/src/pages/projectDetail/projectDetail.gql
  frontend/src/pages/projectList/ProjectList.tsx
Labels: 新機能, フロントエンド

#310 fix: メンバーホバー時の挙動を改善
  frontend/src/components/models/projectList/ProjectListDetail.tsx
  frontend/src/components/models/task/TaskColumn.tsx
  frontend/src/components/models/task/TaskComment.tsx
  frontend/src/components/models/task/TaskEditOverviewField.tsx
  frontend/src/components/models/task/TaskEditTitleField.tsx
  frontend/src/components/models/user/UserAccountSettingModal.tsx
  frontend/src/components/ui/avatar/UserAvatarIcon.tsx
  frontend/src/components/ui/button/GorgeousButton.tsx
  frontend/src/components/ui/button/InputCancelButton.tsx
  frontend/src/components/ui/form/CalenderField.tsx
  frontend/src/components/ui/form/InputField.tsx
  frontend/src/components/ui/form/SelectField.tsx
  frontend/src/components/ui/form/TextAreaField.tsx
  frontend/src/components/ui/popup/HoverTriggerPopover.tsx
  frontend/src/hooks/useControlTextArea.ts
  frontend/src/hooks/useHover.ts
  frontend/src/hooks/useHoverPopper.ts
  frontend/src/pages/projectList/ProjectList.tsx
  frontend/src/styles/theme.ts
Labels: FIX, フロントエンド, 改善

#311 refactor: ProjectDetail.tsx
  frontend/public/svg/quiestclear.svg
  frontend/src/components/ui/header/ProjectDetailHeader.tsx
  frontend/src/hooks/useProjectDetailDragEnd.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectDetail/getUser.gql
  frontend/src/types/status.ts
  frontend/src/utils/controlList.ts
  frontend/src/utils/controlTask.ts
Labels: リファクタ, フロントエンド

#319 fix: 招待URLからプロジェクトに参加した後の挙動を修正
  frontend/src/pages/invitation/index.tsx
Labels: バグ, フロントエンド

#333 fix: 完了リストにあるタスクのステータスポイントを変更できないように
  frontend/src/components/models/task/TaskEditModal.tsx
  frontend/src/components/models/task/TaskEditStatusPointField.tsx
  frontend/src/components/models/task/TaskStatusPointField.tsx
Labels: FIX, フロントエンド

#330 fix: 「パーティー」の文言を統一
  frontend/src/components/ui/form/SearchMemberField.tsx
Labels: FIX, フロントエンド

#327 fix: リストが少しスクロールしてしまう問題を修正
  frontend/src/components/models/project/ProjectDrawer.tsx
Labels: スタイリング, FIX, フロントエンド

#322 fix: currentUser関連のsubscriptionの分割
  frontend/src/hooks/subscriptions/useFetchSubscriptionCurrentUserDataFromProjectDetail.ts
  frontend/src/hooks/subscriptions/useFetchSubscriptionCurrentUserFromMyPage.ts
  frontend/src/hooks/subscriptions/useFetchSubscriptionCurrentUserFromProjectList.ts
  frontend/src/hooks/subscriptions/useNotificationSubscription.ts
  frontend/src/hooks/subscriptions/useUserByTaskSubscription.ts
  frontend/src/hooks/useGetCurrentUserData.ts
  frontend/src/pages/mypage/MyPage.tsx
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/pages/projectList/ProjectList.tsx
Labels: フロントエンド, 改善

#332 bugfix: 他のリスト → 完了リスト / 完了リスト → 他のリストに移動したらアサイン用のInputができるように
  api/src/schema.gql
  api/src/tasks/tasks.resolver.ts
  frontend/src/hooks/useProjectDetailDragEnd.ts
  frontend/src/pages/projectDetail/projectDetail.gql
Labels: バグ, バックエンド, フロントエンド

#336 add: プロジェクト終了時のアニメーションを付与
  frontend/public/svg/project__quest-clear.svg
  frontend/src/components/models/project/ProjectClearOverlay.tsx
  frontend/src/components/ui/modal/Modal.tsx
  frontend/src/hooks/useProjectDetailDragEnd.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/styles/animation/projectClearAnimation.ts
Labels: スタイリング, 優先度: 高, フロントエンド

#337 feat: プロジェクト一覧ページの3Dモデルのバックグランドに背景を追加
  frontend/public/cgBackground/afternoon.webp
  frontend/public/cgBackground/morning.webp
  frontend/public/cgBackground/night.webp
  frontend/src/components/models/cg/CgAvatarContainer.tsx
  frontend/src/components/models/cg/CgAxesHelper.tsx
  frontend/src/components/models/cg/CgCanvasWrapper.tsx
  frontend/src/components/models/egg/EggAvatar.tsx
  frontend/src/components/models/monster/MonsterAvatar.tsx
Labels: 新機能, 優先度: 高, フロントエンド, 改善

#347 bugfix: ステータスポイントの更新がんできるように
  api/src/tasks/tasks.service.ts
Labels: バグ, バックエンド

#349 fix: タスクのユーザーアサイン時にプロジェクト全体から検索されてしまう問題の修正
  frontend/.eslintrc.json
  frontend/src/components/models/employee/EmployeeProjectMembers.tsx
  frontend/src/components/models/project/ProjectDrawer.tsx
  frontend/src/components/models/projectList/ProjectListCreateModal.tsx
  frontend/src/components/models/task/TaskCard.tsx
  frontend/src/components/models/task/TaskColumn.tsx
  frontend/src/components/models/task/TaskColumnList.tsx
  frontend/src/components/models/task/TaskCreateModal.tsx
  frontend/src/components/models/task/TaskEditModal.tsx
  frontend/src/components/models/task/TaskList.tsx
  frontend/src/components/ui/form/SearchMemberField.tsx
  frontend/src/components/ui/form/SearchMemberFieldFromProjectCreate.tsx
  frontend/src/components/ui/header/ProjectDetailHeader.tsx
  frontend/src/components/ui/popup/InvitationPopup.tsx
  frontend/src/components/ui/popup/SearchTaskPopup.tsx
  frontend/src/hooks/useModalInterlockingScroll.ts
  frontend/src/hooks/useSearchSameCompanyMember.ts
  frontend/src/hooks/useSearchSameProjectMember.ts
  frontend/src/hooks/useTaskUserSelectForm.ts
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/types/groups.ts
Labels: バグ, 優先度: 高, フロントエンド

#331 bugfix: リストを作成してから削除すると二つ消えるバグの修正
  api/src/lists/lists.service.ts
Labels: バグ, バックエンド

#345 fix: 完了リストにあるタスクを削除した場合の経験値などを再計算
  api/src/tasks/tasks.resolver.ts
  api/src/tasks/tasks.service.ts
Labels: FIX, バックエンド

#342 add: プロジェクト終了後にタスク移動/編集を禁止
  frontend/public/svg/create-list_button.svg
  frontend/src/components/models/project/ProjectClearOverlay.tsx
  frontend/src/components/models/project/ProjectDrawer.tsx
  frontend/src/components/models/project/ProjectRight.tsx
  frontend/src/components/models/task/TaskCard.tsx
  frontend/src/components/models/task/TaskColumn.tsx
  frontend/src/components/models/task/TaskColumnList.tsx
  frontend/src/components/models/task/TaskEditModal.tsx
  frontend/src/components/models/task/TaskList.tsx
  frontend/src/components/ui/button/CreateListButton.tsx
  frontend/src/components/ui/button/CreateTaskButton.tsx
  frontend/src/components/ui/header/ProjectDetailHeader.tsx
  frontend/src/components/ui/popup/SearchTaskPopup.tsx
  frontend/src/pages/projectDetail/ProjectDetail.tsx
  frontend/src/styles/animation/projectClearAnimation.ts
  frontend/src/styles/theme.ts
Labels: 優先度: 高, フロントエンド
