Repository team-essence/TAoSK, pull requests merged in 2022-01, with the labels that each got.

#360 fix: プロジェクト作成時にログインしているユーザーが自動アサインされないバグの修正 #358
  frontend/src/hooks/useProjectCreateForm.ts
  frontend/src/hooks/useSearchSameCompanyMember.ts
Labels: バグ, 優先度: 高, フロントエンド

#356 fix: ゲームログを二重に取得している #355
  frontend/src/hooks/useGameLog.ts
Labels: FIX, フロントエンド

#359 bugfix: プロジェクト作成時のsubscriptionを取りやめ
  api/src/projects/projects.resolver.ts
  api/src/projects/projects.service.ts
  api/src/schema.gql
  frontend/src/components/models/projectList/ProjectListCreateModal.tsx
  frontend/src/hooks/subscriptions/useFetchSubscriptionCurrentUserFromProjectList.ts
  frontend/src/hooks/useProjectCreateForm.ts
  frontend/src/pages/projectDetail/getUser.gql
  frontend/src/pages/projectList/ProjectList.tsx
  frontend/src/pages/projectList/projectList.gql
Labels: バグ, バックエンド, フロントエンド

#362 fix: プロジェクト一覧のアニメーションを速く
  frontend/src/components/models/projectList/ProjectListItem.tsx
Labels: スタイリング, フロントエンド

#365 feat: ボタンで背景を切り替える
  frontend/public/cgBackground/normal.webp
  frontend/src/components/models/cg/CgCanvasWrapper.tsx
  frontend/src/components/models/monster/Dragon1125.tsx
  frontend/src/components/models/monster/MonsterAvatar.tsx
Labels: 新機能, フロントエンド

#367 fix: azure storageからモデルを取得
  frontend/src/components/models/egg/Egg.tsx
  frontend/src/components/models/monster/Dragon1125.tsx
Labels: FIX, フロントエンド

#369 feat: api側のデプロイする際に必要なファイルの追加&脳波のsubscriptionの追加&envの追加
  api/.deployment
  api/.vscode/settings.json
  api/.yarnrc
  api/src/app.module.ts
  api/src/brain-waves/brain-waves.controller.ts
  api/src/main.ts
  api/src/schema.gql
  api/src/users/users.resolver.ts
  frontend/src/hooks/subscriptions/useFetchSubscriptionCurrentUserDataFromProjectDetail.ts
  frontend/src/hooks/subscriptions/useUpdateUserByBrainSubscription.ts
  frontend/src/hooks/useProjectDetailDragEnd.ts
  frontend/src/pages/projectDetail/getUser.gql
Labels: 優先度: 高, バックエンド

#372 fix: socket通信の修正
  api/src/tasks/tasks.service.ts
Labels: バグ, バックエンド

#374 feat: ARに必要なcontrollerを追加
  api/src/brain-waves/brain-waves.controller.ts
  api/src/tasks/tasks.service.ts
  api/src/users/users.service.ts
Labels: 新機能, バックエンド

#377 bugfix: プロジェクト作成時にリストが4つ作成されるバグの修正 #376
  api/src/projects/projects.service.ts
Labels: バグ, バックエンド

#379 bugfix: CGの背景が一つだけ表示されない問題の修正
  frontend/public/cgBackground/normal.jpg
Labels: バグ, フロントエンド
